# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build common
      run: go build -v github.com/glennhartmann/aoclib/common

    - name: Test common
      run: go test -v github.com/glennhartmann/aoclib/common

    - name: Build doubly_linked_list
      run: go build -v github.com/glennhartmann/aoclib/doubly_linked_list

    - name: Build heap
      run: go build -v github.com/glennhartmann/aoclib/heap

    - name: Build internal/stackqueuebase
      run: go build -v github.com/glennhartmann/aoclib/internal/stackqueuebase

    - name: Test internal/stackqueuebase
      run: go test -v github.com/glennhartmann/aoclib/internal/stackqueuebase

    - name: Build queue
      run: go build -v github.com/glennhartmann/aoclib/queue

    - name: Test queue
      run: go test -v github.com/glennhartmann/aoclib/queue

    - name: Build stack
      run: go build -v github.com/glennhartmann/aoclib/stack

    - name: Test stack
      run: go test -v github.com/glennhartmann/aoclib/stack
